# Study A Task 2. The Study A Proposal {#task2a}

For Tasks 2-3 in Study A, you will work with a group of five other students, which will be established in class on 2019-09-24. If you are working on the project with a partner, then your partner will need to be part of the same small group as you. We will have 10 small groups, most with six students each.

In Study A, you will survey your fellow students through a Google Form (in total, the form will include somewhere around 100 items) that we will develop in Tasks 2-4 and then administer in the final week of October (as Study A Task 6). 

- Students will develop the items for this instrument in 10 groups of 6 people per group. 
- The final survey will include questions generated by each of the 10 groups, plus questions pre-specified by Dr. Love that are identified below.

Survey respondents (de-identified, of course) will include all students in the current 431 class, plus the teaching assistants, and perhaps some volunteers from previous iterations of the course, in an effort to get a reasonable (but by no means random or representative) sample of graduate students at CWRU. 

Remember that Study A is about making comparisons between groups.

## The Task

In this Task, your small group will 

1. develop and propose 2-3 "research questions" for Study A (The Class Survey). 
2. develop and propose 6-10 "homemade" survey items for Study A that relate to your research questions.
3. identify and propose a "scale" of items for Study A (The Class Survey). 

## The Research Questions

> A research question is the fundamental core of a research project, study, or review of literature. It focuses the study, determines the methodology, and guides all stages of inquiry, analysis, and reporting. [Source](https://researchrundowns.com/intro/writing-research-questions/)

- The research questions your project group will prepare for Study A should state the study objective in terms that allow us to apply statistical methods to test data to obtain an answer.
- Each research question should be written in the form of a comparison of 2-3 exposures or groups in terms of an outcome. 
- At least one of your research questions needs to compare groups on a quantitative outcome, and at least one needs to compare groups on a categorical outcome (which could be ordinal or nominal, but which must contain no more than 5 categories.)

Quoting Roger Peng, from [Exploratory Data Analysis with R](https://bookdown.org/rdpeng/exdata/):

> Formulating a question can be a useful way to guide the exploratory data analysis process and to limit the exponential number of paths that can be taken with any sizeable dataset. In particular, a sharp question or hypothesis can serve as a dimension reduction tool that can eliminate variables that are not immediately relevant to the question. For example, (suppose that we are interested in) looking at an air pollution dataset from the U.S. Environmental Protection Agency (EPA). 

> A general question one could ask is "Are air pollution levels higher on the east coast than on the west coast?" But a more specific question might be "Are hourly ozone levels on average higher in New York City than they are in Los Angeles?"

> Note that both questions may be of interest, and neither is right or wrong. But the first question requires looking at all pollutants across the entire east and west coasts, while the second question only requires looking at single pollutant in two cities. It's usually a good idea to spend a few minutes to figure out what is the question you're really interested in, and narrow it down to be as specific as possible (without becoming uninteresting).

## Research Questions that have worked in the past

For Study A, your research questions will need to compare two or more exposure groups on a quantitative outcome (in one case) and on a categorical outcome (in another case). Here are several examples that worked in the past:

- "Do messy people tend to have higher levels of self-described creativity than organized people?"
- "Is whether you voted in the last presidential election strongly associated with your level of interest in the current election?"
- "Does being in a committed romantic relationship result in higher self-esteem compared to not being in a committed romantic relationship?"
- "Do conscientious people spend more time every week engaged in activities, such as exercise, thought to promote health and well-being compared to others?"
- "Do graduate students who routinely pack their lunch have a lower BMI than graduate students who routinely purchase their lunch?"
- "Do individuals who spend a lot of time on social media each day have more or less social anxiety than those who do not?"

Don't boil the ocean here. You're looking for a research question that can be reasonably addressed in a survey of 60-65 people, so it has to be pretty straightforward.

## Checklist for Research Questions

1. Is our research question (RQ) something that we are curious about and that others might care about? 
2. Does our RQ present an issue on which we can justify a stand prior to data collection about what we think will happen?
3. Is our RQ too broad, too narrow, or OK, given the time frame and restrictions of this survey?
4. Is our RQ measurable? What type of information do we need? Can I find a way to ask a limited number of survey questions in such a way to allow me to (after the data are collected) either support or contradict a position on my RQ? 
- Adapted from [this online tutorial from Empire State College](http://www8.esc.edu/htmlpages/writerold/menus.htm#develop)

## Tips on Writing Good Research Questions

- [Duke](https://sites.duke.edu/urgws/files/2014/02/Research-Questions_WS-handout.pdf) has a nice overview online of key issues.
- [Vanderbilt](https://www.vanderbilt.edu/writing/wp-content/uploads/sites/164/2016/10/Formulating-Your-Research-Question.pdf) has some nice materials, built from the [tutorial at Empire State College](http://www8.esc.edu/htmlpages/writerold/menus.htm#develop) quoted earlier
- Jeff Leek provides several relevant tips in *The Elements of Data Analytic Style*
- https://researchrundowns.com/intro/writing-research-questions/ has some excellent tips on wording.

## Proposing 6-10 Survey Items

Task 2 also requires your group to identify and propose 6-10 survey items for Study A (The Class Survey). 

Your group will need to specify the exact wording for your survey items (and potential answers for any categorical responses.) This will likely require some editing and rework, once we have the complete set of proposed items from all students. Be prepared to revise and resubmit, quickly, so that all items can be resolved in time for publication of the draft survey.

Of your 6-10 survey items ...

- at least two should ask the respondents to provide you with a **number** that expresses a quantitative outcome of interest to you, and these outcomes should relate closely to at least one of your research questions.
    - If you are asking people to respond to a prompt using a rating, that rating should be expressed on a wide scale. Our preference is a 0-100 scale for quantitative items, where 0 represents the most negative reaction and 100 the most positive reaction to the item. 
    - One common choice is to make a statement and ask for agreement with that statement on a scale from 0 = Strongly Disagree to 100 = Strongly Agree. 
    - The reason we prefer a 0-100 scale is to increase variation in our responses, as compared to, say, a 1-10 scale. 
    - When responding to items using a scale like this on the actual survey, please use the whole scale.
- **at least two** should ask the respondents to provide you with a response that expresses a categorical outcome of interest to you, and these, too, should relate to at least one of your research questions.
    - You will need to specify each of the available responses that you wish to use in the survey. 
    - No more than five options for your categorical outcome, please.
    - The response options you specify should be mutually exclusive and collectively exhaustive.
- **at least two** should ask the respondents to categorize themselves into one of two (or three) groups. 
    - Be aware that you will need to have at least 10 students in each group in order to build a semi-reasonable analysis.
    - You should expect that 60-65 people will actually respond to the survey, in total. 
    - Again, these groupings should be linked to your research questions.

You are welcome to submit exactly 6, or as many as 10 total survey items in this part of the Task. It is likely that some of your survey items will not correspond to some of your research questions, and that's OK, but each survey item should be linked to at least one of your research questions.

## 15 Items We'll Include

The following items will be included in the survey to identify "groups" of students in a reasonable way. As a result, you should not ask these items in your proposed list, although you can and should consider whether these groupings would be good candidates for application to your research questions.

The following 7 items will have yes/no responses, and thus produce binary groups for analysis.

1. Were you born in the United States? 
2. Is English the language you speak better than any other? 
3. Do you identify as female?
4. Do you wear prescription glasses or contact lenses?
5. Before taking 431, had you ever used R before?
6. Are you currently married or in a stable domestic relationship?
7. Have you smoked 100 cigarettes or more in your entire life?

The next eight items generate non-binary responses. Together, after the survey is complete, we will identify "cutpoints" for these eight items to identify groups of meaningful size. 

8. In what year were you born?
9. How would you rate your current health overall (Excellent, Very Good, Good, Fair, Poor)
10. For how long, in months, have you lived in Northeast Ohio?
11. What is your height in inches? (If you are five feet, eight inches tall, please write 68 inches. To convert from centimeters to inches, multiply your height in centimeters by 0.3937, and then round the result to the nearest inch.)
12. What is your weight in pounds? (To convert from kilograms to pounds, multiply your weight in kilograms by 2.2046, and then round the result to the nearest pound.)
13. What is your pulse rate, in beats per minute? (Please either use a tracking device, or count your pulse for 15 seconds then multiply by 4)
14. Last week, on how many days did you exercise? (0 - 7)
15. Last night, how many hours of sleep did you get?

## Permitted Types of Items

No personal information of any kind related to anything about sex, drugs, or performance in 431 can be asked anywhere in the survey.

The survey will be conducted using a Google Form, rather than Survey Monkey or some other tool. Thus, we have a somewhat restricted set of item types.

For **quantitative measures**, Google Forms permit the use of

1. a *short answer* item without any restrictions on the response (except a character limit)
2. a *short answer* item where respondents are forced to insert a number within a given range through a validation process that only accepts the response if it falls within the specified limits.
3. *linear scale* items for ordered categorical ratings (but only on a scale of up to ten points - i.e. 1 to 10)

For **categorical measures**, Google Forms permit the use of 

1. *multiple choice* items for endorsing a single choice from a group of 2-10 alternatives.
2. *checkbox* items for the endorsement of one or more choices from a group of 2-10 alternatives.
3. *linear scale* items for ordered categorical ratings (often on a 1-X scale, where X is between 2 and 10)
4. *dropdown* items for selections of one option from a group of 2-3 choices.

## Old Class Surveys

The surveys (each containing at least 100 items) from [2014](https://github.com/THOMASELOVE/2019-431-project/blob/master/oldsurveys/2014_431_class_survey.pdf), [2015](https://github.com/THOMASELOVE/2019-431-project/blob/master/oldsurveys/2015_431_class_survey.pdf), [2016](https://github.com/THOMASELOVE/2019-431-project/blob/master/oldsurveys/2016_431_class_survey.pdf), [2017](https://github.com/THOMASELOVE/2019-431-project/blob/master/oldsurveys/2017_431_class_survey.pdf), and
[2018](https://github.com/THOMASELOVE/2019-431-project/blob/master/oldsurveys/2017_431_class_survey.pdf) are available as PDF documents on our web site.

Remember that the rules used this year have been modified from what has been used for the project previously.

## Specifying a "Scale"

Task 2 also requires your group to identify and propose a "scale" of items for Study A (The Class Survey). 

Your group needs to specify a **published** scale (available for free public use) to generate an outcome or grouping(s) of interest from those completing the survey. You will have to provide a complete reference to the scale (online, ideally) and specify each of the items in the scale, and how the scale is then evaluated, in all necessary detail to allow us to review and replicate the scale in practice. 

The word "scale" is used in many different ways. In this case, by a scale I mean a **published** list of items, usually accompanied by a scoring rubric that provides some sort of composite score or scores. Examples of scales we have used in the past include:

- Two [Health Consciousness Scales](https://chirr.nlm.nih.gov/health-orientation.php), one due to Gould another to Dutta-Bregman [Gould Health Consciousness Scale](https://chirr.nlm.nih.gov/health-orientation.php)
- The [Ten-Item Personality Inventory](https://gosling.psy.utexas.edu/scales-weve-developed/ten-item-personality-measure-tipi/ten-item-personality-inventory-tipi/)
- The [Perceived Stress Scale](https://das.nh.gov/wellness/Docs/Percieved%20Stress%20Scale.pdf)
- The [Epworth Sleepiness Scale](https://www.sleepapnea.org/assets/files/pdf/ESS%20PDF%201990-97.pdf)

Your group will need to verify explicitly in your Task 2 materials that the scale your group proposes is freely available for use by anyone, without any fees or registration requirements.

## Deadline and Submission information

The deadline is **2019-10-08 at 5 PM** for Study A Task 2. Note that the same deadline applies to Study B Task 2.

One member of your small group will submit Study A Task 2 for the entire group, by sharing a Google Doc with Professor Love via email directly to him. Be sure that Professor Love receives the email invitation by 5 PM. 

- The document should, of course, be shared with all members of your small group.
- The Google Doc should contain, at the top, the names of all members of the group and the group name, followed by three sections, labeled as follows...

```
A. Our research questions 
B. Our "homemade" survey items for Study A
C. Our "scale" of items for Study A
```

### "Grading"

Professor Love will suggest revisions to these materials as quickly as possible (likely on the same day as they are due), will assign a grade of OK or REDO, then share the revised document to the Google Drive, and email all members of the group to let you know that his review is complete. 

If your group receives a REDO, your group will need to complete that revision (as a group) within 24 hours. Multiple REDOs are rarely necessary, but a single REDO is very, very common. All revisions will need to be complete in time for Dr. Love to generate the Draft Survey by 2019-10-14, so fast feedback is required.

Once your group receives a grade of OK, you are done with Study A Task 2. Successful completion of Task 2 is a requirement before you can proceed on to subsequent Tasks for Study A.

You will receive 15 points once you have successfully completed Tasks 2, 3, 4 and 5 for Study A in a timely fashion.

