# Study A Task 3. Review/Edit Draft Survey Items {#task3a}

For Tasks 2-3 in Study A, you will work with a group of other students, which will be established in class on 2019-09-24. If you are working on the project with a partner, then your partner will need to be part of the same small group as you. We will have 15 small groups, most with four students each.

In Task 3 for Study A, your small group will submit a single Google Doc (probably only one page, 12 point font, with each of your full names and Study A Task 3 clearly indicated on the top of the Google Doc) containing the following two things: 

## A list of corrections and clarifications to the existing items in the Draft Survey.

This should include any typographical errors, clarifications or other edits that you wish to suggest for the items included in the Draft Survey. Dr. Love anticipates posting the Draft Survey on 2019-10-14.

- If you found no errors or items in need of clarification, write a sentence saying that. 
- If you did find an issue, please be sure to specify the item number where you feel a revision is needed. 

**An Important Note**: In addition, If you see any items in the Draft Survey that you, personally, are not comfortable answering, for whatever reason, **please indicate that to us** in your response here, and we will consider revisions appropriately.

## A list of 0-3 new items that your group wants us to consider adding to the Draft Survey.

- Note that your new items *can* be but do not *need* to be anything you've previously suggested.
- Please begin with the following sentence: `I would like to submit # new items for consideration.` 
    - If your number of new items to suggest is zero, then you need not write anything else here.     
    - Should you wish to have us include 1-3 additional items, remember that nothing about sex, drugs, or performance in 431 can be asked.
    
For each new item you propose...

1. list the complete wording of the new item, being sure to specify the type (for instance, short answer, multiple choice, or checkbox) and the set of possible responses, as you did in Task 2.
2. describe (in 2-3 complete sentences per new item) your reasons to include the item. 
    - Good reasons would begin with a statement of what you intend to do. As an example of such a statement, consider `I wish to study the result of this new item as a quantitative outcome across groups established by current item #*** from the survey.` Or, perhaps, something like: `I wish to use this new item as a grouping variable to study current item #***.` 
    - In either case, follow your statement with a short explanation as to why your new item's result is of interest, and is not already captured by the existing survey.

We will not consider more than 3 new items from any group, and are eager to hold the total set of new items to 20 or less, across all groups. 

## Deadline and Submission information

The deadline is **2019-10-18 at 2 PM** for Study A Task 3. 

One member of your small group (of six people) will submit Study A Task 3 for the entire group, by sharing a Google Doc with Professor Love via email directly to him. Be sure that Professor Love receives an email indicating that the Task 3 form is ready for his review. 

- The document should, of course, be shared with all six members of your small group.
- The Google Doc should contain, at the top, the names of all members of the group and the group name, followed by two sections, labeled as follows:

A. Our corrections/clarifications to the draft survey
B. Our new proposed items for the survey

### "Grading"

Professor Love will acknowledge successful completion of Task 3 to your group as soon as possible. There is no grade for this Task, but it is a mandatory part of the project. 

If he requires clarification on your materials, he will return the Doc with comments, and your group will have 24 hours to respond. The final version of the survey will be posted on 2019-10-23, so timely feedback will be crucial.

You will receive 15 points once you have successfully completed Tasks 2, 3, 4 and 5 for Study A in a timely fashion.
