# Study A Task 4. Taking the Survey {#task4a}

In this Task, you, individually, will take the Survey that we have been creating.

## Deadline and Submission information

Submit your answers to the course survey via the Google Form that will be linked at http://bit.ly/2019-431-survey.

- The final item on the survey will ask for your name, and the system is collecting your email address (you must be logged into Google via CWRU). These will be pruned from the survey before data sets are created.
    - You should answer all of the items. Please don't skip any items you can answer. Your colleagues need data.
    - If you want to save your work and return later, note that only the *first* item in each section of the survey must be completed for Google to let you submit your work. Once you've submitted a partially completed survey, you can return as often as you like before the deadline to finish up.
    
### "Grading"

Successful completion of the Survey is a required Task for the Project.

You will receive 15 points once you have successfully completed Tasks 2, 3, 4 and 5 for Study A in a timely fashion.

## Receiving Your Study A Data 

Once the Survey is complete, Professor Love will post **multiple** data files, each containing some of the variables you need.

- You will need to download all of the files, and then *combine* and tidy to suit your needs. Combining data sets like this is a skill you'll need to master to successfully complete the Project.
- The files will be linked by the subject identification number, probably called `subject`. 

### On Merging the Data Files

When you get the files, you'll need to *merge* or *join* them, in R, rather than in Excel or something like that. To learn more about the options here, I suggest:

1. RStudio's [Data Transformation Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf) has some descriptions of methods for Combining Tables, with illustrations.
2. The [folks at STAT545 have a great "cheat sheet" on this](https://stat545.com/join-cheatsheet.html) as well, which has a more expansive description of some of the ideas.
3. The material on [Relational Data in R for Data Science](https://r4ds.had.co.nz/relational-data.html) should also give you a useful introduction to the ideas and code involved.


