# Study B Task 4. Sharing Your Raw Data {#task4b}

## The Task

Study B Task 4 requires you to share your data for Study B. The model for this Task (and Task 5) is Jeff Leek's [Guide to Data Sharing](https://github.com/jtleek/datasharing), which you should definitely read.

Specifically, you will submit a direct link to the raw data set (without any need for me to sign up for anything) or a .csv copy of the raw and de-identified data set (containing only the variables you plan to use in your actual project work) which you should call `yourname-raw.csv`.

You will need, as well, to include a few sentences that convince me that the "raw", de-identified data you are submitting are completely free of any restrictions (after de-identification and compliance with all HIPAA and other security standards), contain NO protected information of any kind, and can be shared freely with the general public. You will need to write a statement asserting that all of this is true for me to approve this Task.

## The Raw Data Set

You need to show me the raw, de-identified data. What does this mean?

- The data set should be as you "received" it, **other** than the following:
    - The "raw" data set must be completely de-identified, by removing any columns containing identifiable information. 
    - The "raw" data you post should include no protected health information, nor should it include anything you are not 100% sure you can share with Dr. Love.
    - The "raw" data set must include a unique id code for each subject, and that can be generated by you if the original data contained identifiable information within its id codes.
    - The "raw" data set may in fact be multiple data sets, which you will merge together to form your eventual, tidy, analytic data set.
    - The "raw" data set must include all variables you will or might use in your project analyses, but you are permitted to delete any variables (columns) that you are 100% sure will NOT be used in your analyses. Note that you should include any variables that you haven't made a final decision on.
    - The "raw" data set should indicate all missing values as they were originally provided to you. Do not impute missing values in the "raw" data set.
    - You should not summarize the raw data in any way, nor should you delete any rows.

A direct link (without me having to sign up for anything) to an appropriate raw data file(s) is preferred, if possible. If this is not possible, then describe the original source(s) of the data carefully, and send instead a .csv file or (files) of the raw data set, called `yourname-raw.csv`^[If you have to send more than one "raw" .csv data set, append numbers after each name, so you'd submit `yourname-raw1.csv`, `yourname-raw2.csv` etc.] If you must zip the raw data set(s), OK.

## Deadline and Submission information

Submit your work on Task 4 for Study B to Canvas. This can be a simple Word document containing the link to the raw data and your responses to the issues raised above, or a Word document and a series of CSV files. 

The deadline is 2019-11-04 at 9 AM.

- *If you are working with a partner*, one of you should submit the materials to Canvas (be sure that both partners' names are on the top of the document) and the other should submit a one-page Word document stating "My partner, INSERT NAME OF PARTNER, has submitted the work on Task 4 for Study B for us."

### "Grading"

Assuming Dr. Love understands what you've sent, he'll mark your work as OK. If he needs revisions, you'll get a REDO, and will need to respond to that REDO within 24 hours.

You will receive 15 points once you have successfully completed Tasks 2, 3, 4 and 5 for Study B in a timely fashion.

