# Study B Task 5. Sharing Tidied Data and Codebook {#task5b}

## The Task

The model for this Task (and Task 4) is Jeff Leek's [Guide to Data Sharing](https://github.com/jtleek/datasharing), which you should definitely read. You will submit:

1. a single tidy .csv file with a name of your choice containing a clean, tidy data set for Study B, along with 
2. a Word, PDF or HTML file containing both 
    a. a **codebook** section which describes every variable (column) and its values in your .csv file, 
    b. a **study design** section which reminds (and updates) us about the source of the data and your research question.

## The Tidy Data Set

Your tidy .csv file should include only those variables you will actually use in your analysis of Study B. Your .csv file should include one row per subject in your data, and one column for each variable you will use. Your data are tidy if each variable you measure is in its own column, and each different observation of that variable is in its own row, identifed by the subject identification code in the left-most column, which you might call `Subj_ID` if that's helpful.

You need to provide:

1. a header row (row 1 in the spreadsheet) that contains full row names. So if you measured age at diagnosis for patients, you would head that column with the name `AgeAtDiagnosis` or `Age_at_Diagnosis` instead of something like `ADx` or another abbreviation that may be hard for another person (or you, two years from now) to understand.
2. a study identification number (I would call this variable `Subj_ID` and use consecutive integers to represent the rows in your data set) which should be the left-most variable in your tidy data.
3. a quantitative outcome with a meaningful name using no special characters other than an underscore (`_`) used to separate words, which should be the second variable in your data.
    + If you have any missing **outcome** values, **delete those rows** entirely from your tidy data set before submitting it.
4. at least four predictor variables, each with a meaningful name using no special characters other than `_` to separate words, and the predictors should be shown in columns to the right of the outcome.
    + *Continuous* variables are anything measured on a quantitative scale that could be any fractional number.
    + *Ordinal categorical* data are data that have a fixed, small (< 100) number of levels but are ordered.
    + *Nominal categorical* data are data where there are multiple categories, but they aren't ordered. 
    + Categorical predictors should read into R as factors, so your categories should include letters, and not just numbers. In general, try to avoid coding nominal or ordinal categorical variables as numbers. 
    + Label your categorical predictors in the way you plan to use them in your analyses.
    + *Missing data* are data that are missing and you don't know the mechanism. Missing data in the predictor variables are allowed, and you should code missing values in your tidy data set as `NA`. It is critical to report if there is a reason you know about that some of the data are missing. 
    + Note that you should **not** impute any data in Project Task 5. Instead, you will impute as part of your analysis and demonstrate that in Tasks 6 and 7.
5. any other variables you need to share with me (typically this would only include things you had to use in order to get to your final choice of outcome and predictors.) Most people will not need to share any additional variables.

I will need to be able to take your submitted tidy `.csv` file and run your eventual Markdown file (part of your portfolio in [Study B Task 6](#task6b)) against it and obtain your results, so it must be completely clean. Because it is a `.csv` file, you'll have no highlighting or bolding or any other special formatting. If you have missing values, they should be indicated as `NA` in the file. If you obtain the file in R, and then write it to a .csv file, you should write the file without row numbers if you already have an identification variable. To do so, you should be able to use `write_csv(dataframeinR, "newfilename.csv")` where you will substitute in the name of your data frame in R, and new (.csv) file name. Don't use the same name for your original data set and your tidy one.

**Note** Your "tidy" `.csv` file should contain no less than 250 and no more than 2,500 rows.

## The Codebook

For almost any data set, the measurements you calculate will need to be described in more detail than you will sneak into the spreadsheet. The code book contains this information. At minimum it should contain:

1. Information about the variables (including units and codes for any categorical variables) in your tidy data set
2. Information about the summary choices or transformations you made or the development of any scales from raw data

By reading the codebook, I should understand what you did to get from the raw data to your tidy data, so add any additional information you need to provide to make that clear.

## The Study Design

Here is where I want you to put the information about the study design you used. You can and should reuse (and edit) the information you have provided in previous Tasks in building this Codebook, updated to mirror your current plan. Specifically, you should provide:

1. Your research question describes your outcome, your key predictor and other predictors, and the population of interest. It is probably easiest to follow one of these formats^[You are welcome to move the clauses around to make for a clearer question.].

- What is the effect of `*your key predictor*` on `*your outcome*` adjusting for `*your list of other predictors*` in `*your population of subjects*`?
- How effectively can `*specify your predictors*` predict `*your outcome*` in `*your population of subjects*`? 

2. A thorough description of the data collection process, with complete details as to the nature of the variables, the setting for data collection, and complete details of any apparatus you used which may affect results that **has not already been covered** in the codebook materials.

3. Specification of the subjects and methods involved.
    a. Who are the subjects under study? How many are included in your final tidy data set?
    b. When were the data gathered? By whom?
    c. What caused subjects to be included or excluded from the study?
    
## Deadline and Submission information

Submit your work on Task 5 for Study B to Canvas. You will need to prepare the codebook and study design sections using R Markdown, and you should submit the R Markdown file along with the Word/PDF/HTML (Dr. Love prefers HTML) output.

The deadline is 2019-12-02 at 2 PM.

- *If you are working with a partner*, one of you should submit the materials to Canvas (be sure that both partners' names are on the top of the document) and the other should submit a one-page Word document stating "My partner, INSERT NAME OF PARTNER, has submitted the work on Task 5 for Study B for us."

### "Grading"

Assuming Dr. Love understands what you've sent, he'll mark your work as OK. If he needs revisions, you'll get a REDO, and will need to respond to that REDO within 24 hours.

You will receive 15 points once you have successfully completed Tasks 2, 3, 4 and 5 for Study B in a timely fashion.
